/**
 * Created by Durgaprasad Budhwani on 12/29/2017.
 */
export const GET_README_CONTENT = 'GET_README_CONTENT';
export const GET_README_CONTENT_RESULT = 'GET_README_CONTENT_RESULT';
export const GET_README_CONTENT_START = 'GET_README_CONTENT_START';
export const GET_README_CONTENT_COMPLETED = 'GET_README_CONTENT_COMPLETED';
export const GET_README_CONTENT_ERROR = 'GET_README_CONTENT_ERROR';
export const ADD_PACKAGES = 'ADD_PACKAGES';
export const ADD_PACKAGES_START = 'ADD_PACKAGES_START';
export const ADD_PACKAGES_COMPLETED = 'ADD_PACKAGES_COMPLETED';
export const ADD_PACKAGE_RESULT = 'SEARCH_PACKAGE_RESULT';
export const ADD_PACKAGE_ERROR = 'SEARCH_PACKAGE_ERROR';
export const SEARCH_PACKAGE = 'SEARCH_PACKAGE';
export const SEARCH_PACKAGE_START = 'SEARCH_PACKAGE_START';
export const SEARCH_PACKAGE_COMPLETED = 'SEARCH_PACKAGE_COMPLETED';
export const SEARCH_PACKAGE_RESULT = 'SEARCH_PACKAGE_RESULT';
export const SEARCH_PACKAGE_ERROR = 'SEARCH_PACKAGE_ERROR';
export const COMPLETED = 'COMPLETED';
export const STARTED = 'STARTED';
export const INPROGRESS = 'INPROGRESS';
